# Generated by Django 3.2.5 on 2021-07-25 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('image_Url', models.CharField(max_length=2083)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Window', 'Window'), ('Toilet', 'Toilet'), ('Bed', 'Bed'), ('Cabinet', 'Cabinet'), ('Table', 'Table'), ('Chair', 'Chair')], max_length=255)),
                ('progress', models.CharField(choices=[('Completed', 'Completed'), ('Uncomplete', 'Uncomplete')], max_length=255)),
                ('created', models.DateTimeField(default=False)),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RecordEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('created', models.DateTimeField()),
                ('remark', models.CharField(max_length=255)),
            ],
        ),
    ]
