# Generated by Django 3.2.5 on 2021-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceequipment',
            name='category',
            field=models.CharField(choices=[('Window', 'Window'), ('Toilet', 'Toilet'), ('Bed', 'Bed'), ('Cabinet', 'Cabinet'), ('Table', 'Table'), ('Chair', 'Chair')], max_length=255),
        ),
    ]
