# Generated by Django 3.2.5 on 2021-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_maintenanceequipment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='created',
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='remark',
            field=models.CharField(default=False, max_length=255),
        ),
    ]
