# Generated by Django 3.2.5 on 2021-07-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20210725_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='hostel',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='remark',
            field=models.CharField(max_length=255),
        ),
    ]
